### ISSUE TITLE
Using mgemu with multiprocessing

### ISSUE THREAD

**Issue by raphkou** [LSSTDESC/mgemu#3]
Hello,

I am trying to use mgemu with emcee and to parallelize it using multiprocessing. I use mgemu in my likelihood function, and it works nicely when I use emcee without multiprocessing. However, when using multiprocessing, there is no error but it seems that nothing happens (the chain doesn't advance).
The problem is related to mgemu because the same code runs without problem when I comment the call to mgemu. 

Would you have any idea why I've got this problem, or have you ever tried to use multiprocessing with mgemu ?

Thank you very much in advance,

Raphaël Kou

**Comment by nesar** [comment]
Thank you for bringing it up, @raphkou. We have not tried it with multiprocessing per se, but we have tried with MPI before. Can you try this [branch](https://github.com/LSSTDESC/mgemu/tree/Speedup) and see if that works for you. 

If that doesn't work, can you post a snippet or a basic working code that demonstrates the issue?

**Comment by raphkou** [comment]
Thank you very much for your answer. I had already tried using MPI, and here is the error I get:

Traceback (most recent call last):
  File "/pbs/home/r/rkou/private/mgemu/fit_multiprocessing_test.py", line 3, in <module>
    from mgemu import emu_fast
  File "/pbs/home/r/rkou/.local/lib/python3.7/site-packages/mgemu-1.0-py3.7.egg/mgemu/__init__.py", line 5, in <module>
    from .emu import *
  File "/pbs/home/r/rkou/.local/lib/python3.7/site-packages/mgemu-1.0-py3.7.egg/mgemu/emu.py", line 29, in <module>
    ALL_GP, ALL_PCA = model_load_all(nRankMax=DEFAULT_PCA_RANK)
  File "/pbs/home/r/rkou/.local/lib/python3.7/site-packages/mgemu-1.0-py3.7.egg/mgemu/load.py", line 80, in model_load_all
    GPm, PCAm = model_load(snap_ID, nRankMax)
  File "/pbs/home/r/rkou/.local/lib/python3.7/site-packages/mgemu-1.0-py3.7.egg/mgemu/load.py", line 47, in model_load
    GPm = saver.load(GPmodel, context=ctx_for_loading)
  File "/pbs/home/r/rkou/.local/lib/python3.7/site-packages/gpflow/saver/saver.py", line 35, in load
    encoded_target = context.serializer(context).load(pathname_or_file_like)
  File "/pbs/home/r/rkou/.local/lib/python3.7/site-packages/gpflow/saver/serializers.py", line 46, in load
    with h5py.File(pathname_or_file_like) as h5file:
  File "/pbs/home/r/rkou/.conda/envs/tf-cpu/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/pbs/home/r/rkou/.conda/envs/tf-cpu/lib/python3.7/site-packages/h5py/_hl/files.py", line 195, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/pbs/home/r/rkou/.local/lib/python3.7/site-packages/mgemu-1.0-py3.7.egg/mgemu/models/GP_smooth_rank6snap0', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)


I think this is due to the fact that mgemu is imported several times when I use MPI, and this is the reason why I then tried to use multiprocessing. 

Here is a small piece of code with which I get the previously mentioned error:

from schwimmbad import MPIPool
import emcee
from mgemu import emu_fast
import numpy as np

def lnlike(omega_m):
    pkratio, k_emu = emu_fast(Omh2=omega_m, ns=0.97, s8=0.8, fR0=1e-5, n=1, z=0.5)
    return -1
    
def lnprob(theta):
    lp = lnprior(theta)
    if not np.isfinite(lp):
        return -np.inf
    return lp + lnlike(theta)

ndim, nwalkers = 1,20

pos = [[np.random.uniform(0.13,0.15)] for i in range(nwalkers)]

filename = "chains/test.h5"
backend = emcee.backends.HDFBackend(filename)

with MPIPool() as pool:
    
    if not pool.is_master():
        pool.wait()
        
    sampler = emcee.EnsembleSampler(nwalkers,ndim,lnprob,pool=pool,backend=backend)
    final_state = sampler.run_mcmc(pos, 2, progress=False)

Thank you very much for your help.
